"""Add purchase  Association Table

Revision ID: 2b09acbe8c28
Revises: 37359a01998e
Create Date: 2023-09-11 18:21:13.204247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b09acbe8c28'
down_revision = '37359a01998e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Bought at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('Product ID', sa.Integer(), nullable=False),
    sa.Column('Product Name', sa.String(), nullable=True),
    sa.Column('Customer ID', sa.Integer(), nullable=False),
    sa.Column('Customer Name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Customer ID'], ['customers.id'], name=op.f('fk_purchases_Customer ID_customers')),
    sa.ForeignKeyConstraint(['Customer Name'], ['customers.name'], name=op.f('fk_purchases_Customer Name_customers')),
    sa.ForeignKeyConstraint(['Product ID'], ['products.id'], name=op.f('fk_purchases_Product ID_products')),
    sa.ForeignKeyConstraint(['Product Name'], ['products.name'], name=op.f('fk_purchases_Product Name_products')),
    sa.PrimaryKeyConstraint('ID', 'Product ID', 'Customer ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases')
    # ### end Alembic commands ###
