"""Added Customer model defined relationship with SaleRepresentative

Revision ID: 37359a01998e
Revises: b9d16d190420
Create Date: 2023-09-11 17:20:51.450205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37359a01998e'
down_revision = 'b9d16d190420'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
