"""Added the seed.py and created salerep seed data

Revision ID: 8512c76ad47f
Revises: aedee4e1ae4d
Create Date: 2023-09-12 11:45:46.647551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8512c76ad47f'
down_revision = 'aedee4e1ae4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Bought at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('Product ID', sa.INTEGER(), nullable=False),
    sa.Column('Product Name', sa.VARCHAR(), nullable=True),
    sa.Column('Customer ID', sa.INTEGER(), nullable=False),
    sa.Column('Customer Name', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['Customer ID'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['Customer Name'], ['customers.name'], ),
    sa.ForeignKeyConstraint(['Product ID'], ['products.id'], ),
    sa.ForeignKeyConstraint(['Product Name'], ['products.name'], ),
    sa.PrimaryKeyConstraint('ID', 'Product ID', 'Customer ID')
    )
    # ### end Alembic commands ###
