"""Added Customer model defined relationship with SaleRepresentative

Revision ID: a797a99b91a8
Revises: 1c577c962828
Create Date: 2023-09-11 17:09:38.937284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a797a99b91a8'
down_revision = '1c577c962828'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('sale_rep', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sale_rep'], ['salesreps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
