"""Added the debug.py model

Revision ID: aedee4e1ae4d
Revises: 2b09acbe8c28
Create Date: 2023-09-12 11:30:50.042474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aedee4e1ae4d'
down_revision = '2b09acbe8c28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
