"""Added Customer model defined relationship with SaleRepresentative

Revision ID: b9d16d190420
Revises: a797a99b91a8
Create Date: 2023-09-11 17:19:45.797303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d16d190420'
down_revision = 'a797a99b91a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
