"""Added the products seed data

Revision ID: edb20d38a3d5
Revises: 8512c76ad47f
Create Date: 2023-09-12 12:20:05.160050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb20d38a3d5'
down_revision = '8512c76ad47f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
